# Trigger tutorial test configuration
# https://twiki.cern.ch/twiki/bin/viewauth/Atlas/RootCore#Package_Makefile

PACKAGE          = L1TopoRDO
PACKAGE_PRELOAD  = 
PACKAGE_CXXFLAGS =
PACKAGE_OBJFLAGS = 
PACKAGE_LDFLAGS  = 
PACKAGE_BINFLAGS = 
PACKAGE_LIBFLAGS = 
PACKAGE_DEP      = 
PACKAGE_TRYDEP   = 
PACKAGE_CLEAN    = 
PACKAGE_NOGRID   = 
PACKAGE_PEDANTIC = 0
PACKAGE_NOOPT    = 0
PACKAGE_NOCC     = 0
PACKAGE_REFLEX   = 0

PACKAGE_PRGDIR = ../utils

include $(ROOTCOREDIR)/Makefile-common
